[[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

[[main]]
  name = "Post"
  weight = 200
  identifier = "post"
  url = "/post/"

[[main]]
  name = "Series"
  weight = 200
  identifier = "series"
  url = "/series/"

[[main]]
  name = "Category"
  weight = 300
  identifier = "categories"
  url = "/categories/"

[[main]]
  name = "About"
  weight = 400
  identifier = "about"
  url = "/about/"
#[[main]]
#  name = "Certifications"
#  weight = 520
#  identifier = "certifications"
#  url = "/certifications/"